### ISSUE TITLE
Metadata History: "lumina: Certificate verification failed: certificate has expired"

### ISSUE THREAD

**Issue by ThisIsMyAltAccount** [tomrus88/OpenLumina#2]
IDA Pro 9.0.240925 - Windows 

IDA Pro 9 Windows installer SHA256: ```e24ae161a8a9d2edde04149c270db3509cb1056841bed0763ae167902f160c9c```

Only patched license check in ```ida.dll```.

1. Open any file in IDA.
2. Analyze
3. Right click in the main ```IDA View-A``` Window.
4. Select ```Lumina``` and click ```Metadata History```.
5. Error message in ```Output``` Window: ```lumina: Certificate verification failed: certificate has expired```

Pulling/Pushing works fine. It looks like the metadata history is looking elsewhere for the history?

**Comment by tomrus88** [comment]
This makes no sense tbh, as it should be using same server for everything. Check what lumina servers you have configured in IDA settings. Metadata history is likely using primary (first) server. I personally don't have this issue, so it's likely something with your configuration...

**Comment by ThisIsMyAltAccount** [comment]
Sorry! I made typo. I meant to ask is the metadata history doing cert validation/checking somewhere else in the ```ida.dll```, not the lumina server settings in IDA.

I think I found my issue due to my weird setup. Originally I was using a leaked beta2 patched ```lumina_server_teams``` that included patched certificate in the binary. The RC1 IDA and Lumina got released and I copied the crack and patched certificate in the binary to the lumina RC1 release. That seems to be the cause of the metadata history warning message.

I'll go look for existing patches for the leaked RC1 ```lumina90_x64linux.run``` (sha256: F438C94D27508D0F6D26DC88B1ECA11B35C1184CD979EC5E3BD566A3EA4D66DB)

**Comment by tomrus88** [comment]
> I meant to ask is the metadata history doing cert validation/checking somewhere else in the `ida.dll`, not the lumina server settings in IDA.

No it's one single place for all TLS connections IDA makes.

**Comment by ThisIsMyAltAccount** [comment]
After running with the "-z 0080000" I think I've found my issue. If the secondary server is blank, doing the metadata history attempts to localhost:443, which gives the invalid cert error message. If I set the secondary server to the same as the first I do not get the cert error message.

**Comment by tomrus88** [comment]
Guess that means this can be closed then.
